name: Sync fork
on:
  schedule:
    # Daily at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync actions/maven-dependency-submission-action -b main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
